ProyectoProgramacion/Controllers/AnularController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProyectoProgramacion.Modelo;
namespace ProyectoProgramacion.Controllers
{
    public class AnularController : Controller
    {
        #region INSTANCIAS
        programacionBDEntities ModeloDB = new programacionBDEntities();
        #endregion

        #region ACTIONRESULT
        // GET: Anular
        public ActionResult AnularFormulario()
        {
            return View();
        }
        /* RETORNA LAS FACTURAS */
        public ActionResult RetornarFacturas()
        {
            List<SP_RETORNAR_FACTURAS_Result> ListaFacturas =
                this.ModeloDB.SP_RETORNAR_FACTURAS().ToList();
            return Json(ListaFacturas);
        }

        /* ANULAR UNA FACTURA */
        [HttpPost]
        public ActionResult AnularFactura(SP_RETORNAR_FACTURAS_Result ModeloVista)
        {
            string mensaje = string.Empty;
            int filas = 0;
            /* CONSULTAMOS PRIMERO PARA VERIFICAR LA FECHA */
            List<SP_RETORNAR_FACTURAS_ID_Result> Factura =
                this.ModeloDB.SP_RETORNAR_FACTURAS_ID(ModeloVista.C_ID_ENCABEZADO_FACTURA).ToList();
            try
            {
                if (Factura.Count > 0)
                {

                    filas = this.ModeloDB.SP_ANULAR_FACTURA(ModeloVista.C_ID_ENCABEZADO_FACTURA);
                }
                else
                {
                    mensaje = "Factura No se puede eliminar tiene mas de 15 días de facturada";
                }
            }
            catch (Exception error)
            {

                mensaje = error.Message;
            }
            finally
            {
                if (filas > 0)
                {
                    mensaje = "Factura Anulada con exito";
                }
            }
            return Json(new
            {
                //retornamos
                resultado = mensaje
            });
        }
        #endregion

    }
}

ProyectoProgramacion/Controllers/CajaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProyectoProgramacion.Modelo;
using System.Net.Mail;
namespace ProyectoProgramacion.Controllers
{
    public class CajaController : Controller
    {
        /* INSTANCIAS DE CLASE */
        #region INSTANCIAS
        programacionBDEntities ModeloDB = new programacionBDEntities();
        #endregion

        /* ACTION RESULT */
        #region ACTIONRESULT
        // GET: Caja
        public ActionResult CajaVista()
        {
            
            return View();
        }
        /* RETORNA LOS PARAMETROS DE LA CAJA */
        [HttpPost]
        public ActionResult RetornarParametros()
        {
            List<SP_RETORNA_PARAMETROS_Result> ListaParametros =
                this.ModeloDB.SP_RETORNA_PARAMETROS().ToList();
            return Json(ListaParametros);
        }

        /* REGISTRA UNA APERTURA DE CAJA */
        [HttpPost]
        public ActionResult RegistrarAperturaCaja(SP_RETORNAR_APERTURA_CAJA_FECHA_Result ModeloVista)
        {
            string mensaje = "";
            int filas = 0;
            /* VALIDAMOS SI EXISTEN REGISTROS DEL DIA */
            List<SP_RETORNAR_APERTURA_CAJA_FECHA_Result> Aperturas =
                this.ModeloDB.SP_RETORNAR_APERTURA_CAJA_FECHA().ToList();
            /* DATOS DEL USUARIO */
            sp_Validar_Inicio_Sesion_Result DatosUsuario =
                (sp_Validar_Inicio_Sesion_Result)this.Session["DatosUsuario"];
            if (Aperturas.Count == 0)
            {
                try
                {
                    filas = this.ModeloDB.SP_REGISTRAR_APERTURA_CAJA(ModeloVista.C_MONTO,
                                                                     DatosUsuario.C_ID_USUARIO);
                }
                catch (Exception error)
                {

                    mensaje = "Error: " + error.Message;
                }
                finally
                {
                    if (filas > 0)
                    {
                        mensaje = "Registro de apertura con exito";
                        /* ENVIAMOS EL CORREO DE LA APERTURA */
                        EnviarCorreoElectronico("1");
                    }
                    else
                    {
                        mensaje = "No se pudo registrar la apertura";
                    }
                }
            }
            else
            {
                mensaje = "Ya existe una apertura de caja con la fecha: " + Aperturas[0].C_FECHA;
            }
            return Json(new {
                resultado = mensaje
            });
        }
        /* REGISTRA UNA APERTURA DE CAJA */
        [HttpPost]
        public ActionResult RegistrarCierreCaja()
        {
            string mensaje = "";
            int filas = 0;
            /* VALIDAMOS SI EXISTEN REGISTROS DEL DIA */
            List<SP_RETORNAR_CIERRES_CAJA_Result> Cierre =
                this.ModeloDB.SP_RETORNAR_CIERRES_CAJA().ToList();
            /* DATOS DEL USUARIO */
            sp_Validar_Inicio_Sesion_Result DatosUsuario =
                (sp_Validar_Inicio_Sesion_Result)this.Session["DatosUsuario"];
            if (Cierre.Count == 0)
            {
                try
                {
                    filas = this.ModeloDB.SP_REGISTRAR_CIERRE_CAJA(DatosUsuario.C_ID_USUARIO);
                }
                catch (Exception error)
                {

                    mensaje = "Error: " + error.Message;
                }
                finally
                {
                    if (filas > 0)
                    {
                        mensaje = "Registro de Cierre con exito";
                        /* ENVIAMOS EL CORREO DE LA APERTURA */
                        EnviarCorreoElectronico("2");
                    }
                    else
                    {
                        mensaje = "No se pudo registrar el cierre";
                    }
                }
            }
            else
            {
                mensaje = "Ya existe un cierre de la caja con la fecha: " + Cierre[0].C_FECHA;
            }
            return Json(new
            {
                resultado = mensaje
            });
        }
        /* RETORNA LAS APERTURAS DE CAJA */
        public ActionResult RetornarAperturasDeCaja()
        {
            List<SP_RETORNAR_APERTURA_CAJA_FECHA_Result> Aperturas =
              this.ModeloDB.SP_RETORNAR_APERTURA_CAJA_FECHA().ToList();
            return Json(Aperturas);
        }
        /* RETORNA LAS CIERRES DE CAJA */
        public ActionResult RetornarCierreDeCaja()
        {
            List<SP_RETORNAR_CIERRES_CAJA_Result> Cierres =
              this.ModeloDB.SP_RETORNAR_CIERRES_CAJA().ToList();
            return Json(Cierres);
        }
        #endregion

        /* METODOS DE CLASE */
        #region METODOS
        /* ENVIAR CORREO ELECTRONICO */
        public void EnviarCorreoElectronico(string tipo)
        {
            try
            {
                /* VARIABLES */
                string Emisor = "andreyazofeifaalvarado@gmail.com";
                string Contraseña = "amsklahsf@185$%3";
                string Receptor = "";
                string Asunto = "";
                string Mensaje = "";
                string Host = "smtp.gmail.com";
                int Puerto = 25;
                /*  CONSULTAMOS LOS PARAMETROS */
                List<SP_RETORNA_PARAMETROS_Result> ListaParametros =
                   this.ModeloDB.SP_RETORNA_PARAMETROS().ToList();
                /* SETEAR VARIABLES */
                /* VALIDAMOS QUE CORREO ENVIAMOS */
                switch (tipo)
                {
                    case "1":
                        /* APERTURA */
                        Receptor = ListaParametros[0].C_CORREO_APERTURA;
                        Asunto = "Apertura de caja";
                        Mensaje = "Apertura de caja con un monto de: " + ListaParametros[0].C_MONTO_MINIMO;
                        break;
                    case "2":
                        /* CIERRE */
                        List<SP_RETORNAR_CIERRES_CAJA_Result> Cierres =
                        this.ModeloDB.SP_RETORNAR_CIERRES_CAJA().ToList();
                        Receptor = ListaParametros[0].C_CORREO_APERTURA;
                        Asunto = "Cierre de caja";
                        Mensaje = "Cierre de caja con un monto de: " + Cierres[0].C_MONTO;
                        break;
                    default:
                        break;
                }
                /* DATOS DEL CORREO */
                MailMessage Correo = new MailMessage();
                Correo.From = new MailAddress(Emisor);
                Correo.To.Add(ListaParametros[0].C_CORREO_APERTURA);
                Correo.Subject = Asunto;
                Correo.Body = Mensaje;
                Correo.IsBodyHtml = true;
                Correo.Priority = MailPriority.Normal;
                /* DATOS DEL SMTP */
                SmtpClient smtp = new SmtpClient();
                smtp.Host = Host;
                smtp.Port = Puerto;
                smtp.EnableSsl = true;
                smtp.UseDefaultCredentials = true;
                smtp.Credentials = new System.Net.NetworkCredential(Emisor, Contraseña);
                smtp.Send(Correo);
            }
            catch (Exception error)
            {

                string m = error.Message;
            }
        }


        #endregion
    }
}

ProyectoProgramacion/Controllers/ModelosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProyectoProgramacion.Modelo;
namespace ProyectoProgramacion.Controllers
{
    public class ModelosController : Controller
    {
        #region INSTANCIAS
        programacionBDEntities ModeloDB = new programacionBDEntities();
        #endregion
        // GET: Modelos
        public ActionResult ModeloVehiculo()
        {
            return View();
        }
        //CONSULTA LOS MODELOS DE VEHICULOS
        [HttpPost]
        public ActionResult MostrarModelos()
        {
            List<SP_RETORNA_MODELO_Result> ListaModelos =
                this.ModeloDB.SP_RETORNA_MODELO(null).ToList();

            return Json(new
            {
                resultado = ListaModelos
            });
        }

        /* REGISTRA LA MODELO DE VEHICULO */
        [HttpPost]
        public ActionResult RegistrarModelo(SP_RETORNA_MODELO_Result ModeloVista)
        {
            string mensaje = "";
            int filas = 0;
            try
            {
                filas = this.ModeloDB.SP_REGISTRAR_MODELO(ModeloVista.C_ID_MARCA,
                                                          ModeloVista.C_NOMBRE_MODELO);
            }
            catch (Exception error)
            {

                mensaje = error.Message;
            }
            finally
            {
                if (filas > 0)
                {
                    mensaje = "Exito al registrar el modelo";
                }
                else
                {
                    mensaje = "No se pudo registrar el modelo, posiblemente ya exista en la base de datos";
                }
            }
            return Json(new
            {
                resultado = mensaje
            });
        }

        /*MODIFICAR MODELO VEHICULO*/
        public ActionResult ModificarModelo(SP_RETORNA_MODELO_Result ModeloVista)
        {
            string mensaje = "";
            int filas = 0;
            try
            {
                filas = this.ModeloDB.SP_MODIFICAR_MODELO(ModeloVista.C_ID_MODELO,
                                                          ModeloVista.C_ID_MARCA,
                                                          ModeloVista.C_NOMBRE_MODELO);
            }
            catch (Exception error)
            {

                mensaje = error.Message;
            }
            finally
            {
                if (filas > 0)
                {
                    mensaje = "Exito al Modificar el modelo";
                }
                else
                {
                    mensaje = "No se pudo Modificar el modelo";
                }
            }

            return Json(new
            {
                resultado = mensaje
            });
        }
    }
}

ProyectoProgramacion/Controllers/PaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProyectoProgramacion.Modelo;
using System.Data.SqlClient;
namespace ProyectoProgramacion.Controllers
{
    public class PaisController : Controller
    {
        /* INSTANCIAS DE CLASE */
        #region INSTANCIAS DE CLASE
        programacionBDEntities ModeloDB = new programacionBDEntities();
        #endregion

        /* METODOS DE LA CLASE */
        #region METODOS
        /* METODO CONSULTA LOS PAISES QUE EXISTEN */
        public void pc_MostrarPais(SP_RETORNA_PAIS_Result ModeloVista)
        {
            this.ViewBag.ListaPais =
                this.ModeloDB.SP_RETORNA_PAIS(ModeloVista.C_NOMBRE_PAIS).ToList();
        }

        /* METODO CONSULTA LOS PAISES POR ID */
        public void pc_MostrarPaisId(SP_RETORNA_PAIS_Result ModeloVista)
        {
            this.ViewBag.ListaPaisId =
                this.ModeloDB.SP_RETORNA_PAIS_ID(ModeloVista.C_ID_PAIS).ToList();

        }
        #endregion

        /* METODOS DE ACTIONRESULT */
        #region METODOS DE ACTION RESULT
        // GET: Pais
        /* MOSTRAMOS LA LISTA DE LOS PAISES */
        public ActionResult MostrarListaPaises(SP_RETORNA_PAIS_Result ModeloVista)
        {
            pc_MostrarPais(ModeloVista);
            return View();
        }

        public ActionResult RegistrarPais()
        {
            return View();
        }
        /* REGISTRAR UN PAIS */
        [HttpPost]
        public ActionResult RegistrarPais(SP_RETORNA_PAIS_Result ModeloVista)
        {
            string mensaje = string.Empty;
            int filas = 0;
            try
            {
                filas = this.ModeloDB.SP_REGISTRAR_PAIS(ModeloVista.C_NOMBRE_PAIS);
            }
            catch (Exception error)
            {

                mensaje = "Error: " + error.Message;
            }
            finally
            {
                if (filas > 0)
                {
                    mensaje = "Registro de País con exito";
                }
                else
                {
                    mensaje = "No se pudo registrar";
                }
                Response.Write("<script language=javascript>alert('" + mensaje + "');</script>");
            }
            return View();
        }
        /* ELIMINA UN PAIS */
        public ActionResult EliminarPais(SP_RETORNA_PAIS_ID_Result ModeloVista)
        {
            string mensaje = string.Empty;
            int filas = 0;
            try
            {
                filas = this.ModeloDB.SP_ELIMINAR_PAIS(ModeloVista.C_ID_PAIS);
            }
            catch (Exception error)
            {

                mensaje = "Error: " + error;
            }
            finally
            {
                if (filas > 0)
                {
                    mensaje = "País Eliminado con exito";
                }
                else
                {
                    mensaje = "No se pudo eliminar el país puede que este relacionado con otra tabla";
                }
                Response.Write("<script language=javascript>alert('" + mensaje + "');</script>");
            }
            return View();
        }
        /* METODO MODIFICA EL NOMBRE DEL PAIS */
        public ActionResult ModificarPais(SP_RETORNA_PAIS_Result ModeloVista)
        {
            pc_MostrarPaisId(ModeloVista);
            return View();
        }
        [HttpPost]
        public ActionResult ModificarNombrePais(SP_RETORNA_PAIS_Result ModeloVista)
        {
            string mensaje = string.Empty;
            int filas = 0;
            try
            {
                filas = this.ModeloDB.SP_MODIFICAR_PAIS(ModeloVista.C_ID_PAIS,
                                                        ModeloVista.C_NOMBRE_PAIS);
            }
            catch (Exception error)
            {

                mensaje = "Error: " + error;
            }
            finally
            {
                if (filas > 0)
                {
                    mensaje = "País modificado con exito";
                }
                else
                {
                    mensaje = "No se pudo modificar el nombre";
                }
                Response.Write("<script language=javascript>alert('" + mensaje + "');</script>");
            }
            pc_MostrarPaisId(ModeloVista);
            return View("ModificarPais");
        }
        #endregion

    }
}

ProyectoProgramacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("CSS", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Imagenes/7.JPG"  width="125" height="50" /><br />
              
            </div>
            <div class="navbar-collapse collapse">
               
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    @{
                        ProyectoProgramacion.Modelo.sp_Validar_Inicio_Sesion_Result DatosUsuario =
                 (ProyectoProgramacion.Modelo.sp_Validar_Inicio_Sesion_Result)this.Session["DatosUsuario"];
                        if (Convert.ToBoolean(this.Session["Logueado"]) == true)
                        {
                            if (DatosUsuario.C_FK_TIPO == 0)
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Clientes</a>
                                    <div class="dropdown-menu" style="background-color:black">
                                        <ul class="nav navbar-nav">
                                            <li>@Html.ActionLink("Registro Clientes", "RegistroCliente", "Cliente")</li>
                                            <li>@Html.ActionLink("Listado Clientes", "MostrarCliente", "Cliente")</li>
                                        </ul>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Vehiculos</a>
                                    <div class="dropdown-menu" style="background-color:black">
                                        <ul class="nav navbar-nav">
                                            <li>@Html.ActionLink("Registro Vehiculos", "RegistraVehiculo", "Vehiculo")</li>
                                            <li>@Html.ActionLink("Listado Vehiculos", "MostrarVevhiculos", "Vehiculo")</li>
                                            <li>@Html.ActionLink("Registro de Tipos", "RegistrarTipo", "TipoVehiculo")</li>
                                        </ul>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Pais</a>
                                    <div class="dropdown-menu" style="background-color:black">
                                        <ul class="nav navbar-nav">
                                            <li>@Html.ActionLink("Registro Pais", "RegistrarPais", "Pais")</li>
                                            <li>@Html.ActionLink("Listado de Pais", "MostrarListaPaises", "Pais")</li>
                                        </ul>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Mantenimientos</a>
                                    <div class="dropdown-menu" style="background-color:black">
                                        <ul class="nav navbar-nav">

                                            <li>@Html.ActionLink("Registrar Fabricante", "ListarFabricanteVehiculo", "Fabricante")</li>
                                            <li>@Html.ActionLink("Registrar Modelo ", "ModeloVehiculo", "Modelos")</li>
                                            <li>@Html.ActionLink("Registrar Marca ", "ListarMarcaVehiculo", "MarcaVehiculo")</li>
                                            <li>@Html.ActionLink("Registrar Servicio ", "Servicio_Producto", "Servicios")</li>
                                            <li>@Html.ActionLink("Registrar Parametro", "Parametros", "Parametros")</li>
                                            <li>@Html.ActionLink("Registrar Vehiculo por Cliente", "VehiculoPorCliente", "VehiculosPorCliente")</li>
                                        </ul>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Caja y Factura</a>
                                    <div class="dropdown-menu" style="background-color:black">
                                        <ul class="nav navbar-nav">
                                            <li>@Html.ActionLink("Mantenimiento de Caja", "CajaVista", "Caja")</li>
                                            <li>@Html.ActionLink("Facturar", "FacturarServicio", "Factura")</li>
                                            <li>@Html.ActionLink("Anular Factura", "AnularFormulario", "Anular")</li>
                                        </ul>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Reportes</a>
                                    <div class="dropdown-menu" style="background-color:black">
                                        <ul class="nav navbar-nav">
                                            <li>@Html.ActionLink("Reportes Servicio Clientes", "Reportes_ServicioCliente", "Reporte_ServicioCliente_")</li>
                                            <li>@Html.ActionLink("Reportes Vehiculo Cliente", "Reportes_VehiculoCliente", "Reporte_VehiculoCliente_")</li>
                                            <li>@Html.ActionLink("Reportes Cierres", "Reportes_CierreCaja", "Reporte_CierreCaja_")</li>
                                        </ul>
                                    </div>
                                </li>
                            }
                            else if (DatosUsuario.C_FK_TIPO == 1)
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Reportes</a>
                                    <div class="dropdown-menu" style="background-color:black">
                                        <ul class="nav navbar-nav">
                                            <li>@Html.ActionLink("Reportes Servicio Clientes", "Reportes_ServicioCliente", "Reporte_ServicioCliente_")</li>
                                            <li>@Html.ActionLink("Reportes Vehiculo Cliente", "Reportes_VehiculoCliente", "Reporte_VehiculoCliente_")</li>
                                            <li>@Html.ActionLink("Reportes Cierres", "Reportes_CierreCaja", "Reporte_CierreCaja_")</li>
                                        </ul>
                                    </div>
                                </li>
                            }


                            <li class="nav-item text-right">
                                <a class="nav-link text-right" href="/Home/Logout">
                                    <button type="button" id="signout" class="btn btn-danger btn-sm text-right text-align-right">
                                        Cerrar Sesion
                                    </button>
                                </a>
                            </li>



                        }
                    }


                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>  © 2020 Copyright: Universidad Castro Carazo, Ing. Andrey Azofeifa Alvarado & Ing. Bryan Mejia</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Validaciones");
    @RenderSection("scripts", required: false)
</body>
</html>